### ISSUE TITLE
Strange error using Hash.new(0) vs {}

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/ruby-enumerables-hash-practice-green-grocer-lab#1]
I used _Hash.new(0)_ to initialize a hash to store and return my values in the _consolidate_cart()_ and passed **spec** tests fine.  However, when I was finishing up _apply_coupons()_ the **spec** tests would not verify my _apply_coupons()_.  

I narrowed the problem down to the use of _Hash.new(0)_ vs _{}_ by exchanging each function's code with known good code.  Once I initialized the return hash with _{}_ the tests passed for my _apply_coupons()_.  

The error I would get when trying to run tests on _apply_coupons()_ was:

     TypeError:
       no implicit conversion of Symbol into Integer

**Comment by sgharms** [comment]
Well, @dan1mal I admire your debugging technique slowly working to test this out! Let me follow your line of logic.

**Comment by sgharms** [comment]
@dan1mal 

Your debugging technique was good. You noticed that something was different between `Hash.new(0)` and `{}` that _somehow_ results in a strange error involving `Symbol`s and `Integer`s. So is there some part about your broken code that involves an `Integer` or a `Symbol`? Odds are that the problem is there.

The error indicates you tried to do something that's normally done with `Integer`s with a `Symbol`. This is a bug in your code, I believe.

Use the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after reviewing your code and consulting AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment
